server.servlet.context-path=/api
spring.application.name=maven-pom-parser

# Server configuration
server.port=8080
# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=xhield-local
spring.data.mongodb.auto-index-creation=true
